'use strict'

mocha.setup('bdd')
mocha.checkLeaks()

require('../adapters/adapters_test')
require('../cache_test')
require('../cell_test')
require('../ciphers/aes_gcm_test')
require('../ciphers/context_test')
require('../ciphers/key_sequence_test')
require('../ciphers/password_test')
require('../config_test')
require('../counters_test')
require('../crypto/crypto_test')
require('../encryption_test')
require('../executor_test')
require('../format/binaries_test')
require('../format/canon_test')
require('../options_test')
require('../path_test')
require('../router_test')
require('../schedule_test')
require('../shard_test')
require('../store_test')
require('../sync/mutex_test')
require('../sync/queue_test')
require('../sync/rwlock_test')
require('../task_test')
require('../verifier_test')

mocha.run()
